// src/llm/grammar/zork2.vocab.ts
import type { Vocab } from './types'
import { TAKE_ACK, DROP_ACK, ABSENCE_PAT, FAILURE_PAT } from './patterns'

export const ZORK2_VOCAB: Vocab = {
  verbsOnly: ['look', 'inventory', 'wait', 'again', 'quit'],
  movement: [
    'north',
    'south',
    'east',
    'west',
    'northeast',
    'northwest',
    'southeast',
    'southwest',
    'up',
    'down',
    'enter',
    'exit',
  ],
  verbs1: [
    'take',
    'drop',
    'open',
    'close',
    'read',
    'examine',
    'move',
    'push',
    'press',
    'kill',
    'turn on',
    'turn off',
  ],
  verbs2: ['unlock', 'lock', 'put', 'give'],
  preps: ['with', 'in', 'on', 'to'],
  nouns: [
    { canonical: 'lamp', synonyms: ['lantern'] },
    { canonical: 'sword' },
    { canonical: 'wand' },
    { canonical: 'key' },
    { canonical: 'door' },
    { canonical: 'candle' },
    { canonical: 'book' },
    { canonical: 'balloon' },
    { canonical: 'dragon' },
    { canonical: 'unicorn' },
    { canonical: 'robot' },
    { canonical: 'button' },
    { canonical: 'cake' },
  ],
  takeAck: TAKE_ACK,
  dropAck: DROP_ACK,
  absencePat: ABSENCE_PAT,
  failurePat: FAILURE_PAT,
}
