// src/llm/grammar/zork1.vocab.ts
import type { Vocab } from './types'
import { TAKE_ACK, DROP_ACK, ABSENCE_PAT } from './patterns'

export const ZORK1_VOCAB: Vocab = {
  verbsOnly: ['look', 'inventory', 'wait', 'again', 'quit'],
  movement: [
    'north',
    'south',
    'east',
    'west',
    'northeast',
    'northwest',
    'southeast',
    'southwest',
    'up',
    'down',
    'enter',
    'exit',
  ],
  verbs1: [
    'take',
    'drop',
    'open',
    'close',
    'read',
    'examine',
    'move',
    'push',
    'eat',
    'drink',
    'kill',
    'turn on',
    'turn off',
  ],
  verbs2: ['unlock', 'lock', 'put', 'give'],
  preps: ['with', 'in', 'on', 'to', 'under'],
  nouns: [
    { canonical: 'lantern', synonyms: ['lamp'], adjectives: ['brass'] },
    { canonical: 'sword', adjectives: ['elvish'] },
    { canonical: 'mailbox', synonyms: ['box'], adjectives: ['small'] },
    { canonical: 'leaflet' },
    { canonical: 'door' },
    { canonical: 'window' },
    { canonical: 'egg', adjectives: ['jeweled'] },
    { canonical: 'rug' },
    { canonical: 'trap door', synonyms: ['trapdoor'] },
    { canonical: 'grating' },
    { canonical: 'bottle' },
    { canonical: 'water' },
    { canonical: 'garlic' },
    { canonical: 'rope' },
    { canonical: 'knife', adjectives: ['nasty'] },
    { canonical: 'troll' },
    { canonical: 'thief' },
    { canonical: 'key' },
    { canonical: 'coffin' },
    { canonical: 'case', synonyms: ['trophy case'] },
    { canonical: 'sceptre' },
    { canonical: 'sack' },
  ],
  takeAck: TAKE_ACK,
  dropAck: DROP_ACK,
  absencePat: ABSENCE_PAT,
}
