// src/llm/lexicon/fr.core.ts
// French core lexicon (game-independent). DATA IS STORED FOLDED: lowercase,
// no diacritics ('epee', 'lache'); fold() normalizes input to match.
// Conjugation is data, not stemming: list the imperative/2nd-person forms
// players actually type (tu + vous). Canonical targets must be extracted-vocab
// verbs — the round-trip suite (Task 14) gates this.
// NOTE on 'inflate': the v3 Z-machine truncates dictionary words to 6 chars,
// so the extracted vocab stores 'inflat'; 'inflate' is the in-game spelling
// players (and the spec'd tests) use, and the Z-parser accepts it.
import type { CoreLexicon } from './types'

export const FR_CORE: CoreLexicon = {
  verbs: {
    // take
    prends: 'take',
    prenez: 'take',
    prend: 'take', // deliberate -s-drop typo variant, highest-traffic verb only
    ramasse: 'take',
    ramassez: 'take',
    attrape: 'take',
    attrapez: 'take',
    saisis: 'take',
    saisissez: 'take',
    // drop (UAT F-M/F-Q traps: pose/lache)
    pose: 'drop',
    poser: 'drop',
    posez: 'drop',
    lache: 'drop',
    lachez: 'drop',
    laisse: 'drop', // 'laisse tomber' idiom wins when present (longest-first)
    laissez: 'drop',
    // throw
    jette: 'throw',
    jetez: 'throw',
    lance: 'throw',
    lancez: 'throw',
    // open/close
    ouvre: 'open',
    ouvrez: 'open',
    ferme: 'close',
    fermez: 'close',
    // examine/read/look
    examine: 'examine',
    examinez: 'examine',
    observe: 'examine',
    observez: 'examine',
    inspecte: 'examine',
    inspectez: 'examine',
    regarde: 'look',
    regardez: 'look',
    lis: 'read',
    lisez: 'read',
    // search/find
    fouille: 'search',
    fouillez: 'search',
    cherche: 'search',
    cherchez: 'search',
    trouve: 'find',
    trouvez: 'find',
    // movement-adjacent in-world verbs
    monte: 'climb',
    montez: 'climb',
    grimpe: 'climb',
    grimpez: 'climb',
    escalade: 'climb',
    escaladez: 'climb',
    traverse: 'cross',
    traversez: 'cross',
    entre: 'enter',
    entrez: 'enter',
    rentre: 'enter',
    rentrez: 'enter',
    sors: 'exit',
    sortez: 'exit',
    pars: 'leave',
    partez: 'leave',
    saute: 'jump',
    sautez: 'jump',
    nage: 'swim',
    nagez: 'swim',
    suis: 'follow',
    suivez: 'follow',
    embarque: 'board',
    embarquez: 'board',
    debarque: 'disembark',
    debarquez: 'disembark',
    // light/extinguish
    allume: 'light',
    allumez: 'light',
    eteins: 'extinguish',
    eteignez: 'extinguish',
    desactive: 'turn off',
    desactivez: 'turn off',
    active: 'activate',
    activez: 'activate',
    // UAT verb traps
    agite: 'wave',
    agitez: 'wave',
    secoue: 'wave',
    secouez: 'wave', // F-N
    sonne: 'ring',
    sonnez: 'ring', // F-X
    remonte: 'wind up',
    remontez: 'wind up', // F-CC
    gonfle: 'inflate',
    gonflez: 'inflate', // F-R
    creuse: 'dig',
    creusez: 'dig',
    attache: 'tie',
    attachez: 'tie',
    noue: 'tie',
    nouez: 'tie',
    detache: 'untie',
    detachez: 'untie',
    denoue: 'untie',
    denouez: 'untie',
    // combat & misc
    tue: 'attack',
    tuez: 'attack',
    attaque: 'attack',
    attaquez: 'attack',
    frappe: 'attack',
    frappez: 'attack',
    cogne: 'attack',
    cognez: 'attack',
    abats: 'kill',
    abattez: 'kill',
    casse: 'break',
    cassez: 'break',
    brise: 'break',
    brisez: 'break',
    detruis: 'destroy',
    detruisez: 'destroy',
    coupe: 'cut',
    coupez: 'cut',
    tranche: 'cut',
    tranchez: 'cut',
    brandis: 'swing',
    brandissez: 'swing',
    mange: 'eat',
    mangez: 'eat',
    avale: 'eat',
    avalez: 'eat',
    bois: 'drink',
    buvez: 'drink',
    pousse: 'push',
    poussez: 'push',
    tire: 'pull',
    tirez: 'pull',
    deplace: 'move',
    deplacez: 'move',
    bouge: 'move',
    bougez: 'move',
    donne: 'give',
    donnez: 'give',
    offre: 'give',
    offrez: 'give',
    mets: 'put',
    mettez: 'put',
    attends: 'wait',
    attendez: 'wait',
    patiente: 'wait',
    patientez: 'wait',
    prie: 'pray',
    priez: 'pray',
    deverrouille: 'unlock',
    deverrouillez: 'unlock',
    verrouille: 'lock',
    verrouillez: 'lock',
    brule: 'burn',
    brulez: 'burn',
    // manipulation & senses
    tourne: 'turn',
    tournez: 'turn',
    leve: 'raise',
    levez: 'raise',
    souleve: 'raise',
    soulevez: 'raise',
    baisse: 'lower',
    baissez: 'lower',
    abaisse: 'lower',
    abaissez: 'lower',
    remplis: 'fill',
    remplissez: 'fill',
    verse: 'pour',
    versez: 'pour',
    touche: 'touch',
    touchez: 'touch',
    frotte: 'rub',
    frottez: 'rub',
    serre: 'squeeze',
    serrez: 'squeeze',
    presse: 'squeeze',
    pressez: 'squeeze',
    sens: 'smell',
    sentez: 'smell',
    renifle: 'smell',
    reniflez: 'smell',
    compte: 'count',
    comptez: 'count',
    joue: 'play',
    jouez: 'play',
    enfile: 'wear',
    enfilez: 'wear',
    embrasse: 'kiss',
    embrassez: 'kiss',
    reveille: 'wake',
    reveillez: 'wake',
    dis: 'say',
    dites: 'say',
    crie: 'yell',
    criez: 'yell',
    hurle: 'yell',
    hurlez: 'yell',
  },
  verbIdioms: [
    { phrase: 'laisse tomber', to: 'drop' },
    { phrase: 'laissez tomber', to: 'drop' },
    { phrase: 'appuie sur', to: 'push' },
    { phrase: 'appuyez sur', to: 'push' },
    { phrase: 'mets en marche', to: 'turn on' },
    { phrase: 'mettez en marche', to: 'turn on' },
    { phrase: 'jette un oeil a', to: 'examine' },
    { phrase: 'mets le feu a', to: 'burn' },
    { phrase: 'mettez le feu a', to: 'burn' },
    { phrase: 'monte a bord', to: 'board' },
    { phrase: 'montez a bord', to: 'board' },
    // UAT-3 N-3: a LEADING prep is only parsed for 'to', so 'entre dans le
    // bateau' missed to the LLM (which emitted 'enter river'). The idiom
    // consumes verb+prep; the remainder resolves as the object.
    { phrase: 'entre dans', to: 'enter' },
    { phrase: 'entrez dans', to: 'enter' },
    { phrase: 'rentre dans', to: 'enter' },
    { phrase: 'rentrez dans', to: 'enter' },
    { phrase: 'leve toi', to: 'stand' },
    { phrase: 'levez vous', to: 'stand' },
  ],
  particleVerbs: [],
  preps: {
    avec: 'with',
    dans: 'in',
    a: 'to',
    au: 'to',
    aux: 'to',
    sur: 'on',
    sous: 'under',
    vers: 'to',
    de: 'from',
  },
  articles: [
    'le',
    'la',
    'les',
    'l',
    'un',
    'une',
    'du',
    'des',
    'mon',
    'ma',
    'mes',
    'ce',
    'cette',
    'ces',
  ],
  pronounsDirect: ['le', 'la', 'les'],
  pronounsContainer: ['dedans', 'dessus'],
  pronounsSelf: ['moi', 'me'],
  metaAliases: {
    inventaire: 'inventory', // fr (migrated from META_ALIASES)
    diagnostic: 'diagnose', // F5
    recommence: 'restart',
    sauvegarde: 'save',
    restaure: 'restore',
    quitte: 'quit',
    points: 'score',
  },
}
