// src/llm/lexicon/fr.zork2.ts
// French → Zork II noun lexicon. KEYS are extracted-vocab canonicals
// (src/llm/grammar/zork2.vocab.ts); VALUES are folded French words/phrases.
// Validated by lexicon/validate.test.ts (key validity, fold idempotence,
// collision gate, FULL coverage). Entries follow the vocab's canonical order.
// Where French genuinely merges objects (cle, porte, sphere, gateau…)
// the same word appears under several canonicals — ambiguity is first-class.
import type { NounLexicon } from './types'

export const FR_ZORK2: NounLexicon = {
  aquarium: ['aquarium'],
  'arcane item': ['alambic', 'velin'], // the workbench clutter (alembic/vellum)
  'baby sea serpent': ['serpent', 'bebe serpent', 'serpent de mer'],
  'bank brochure': ['brochure', 'depliant'],
  'barred window': ['fenetre a barreaux', 'fenetre'],
  basket: ['nacelle', 'panier', 'ballon', 'montgolfiere'], // the wicker balloon
  'beautiful princess': ['princesse'],
  'black crystal sphere': ['sphere noire', 'boule noire', 'sphere'],
  'black obsidian stand': ['socle d obsidienne', 'socle noir', 'socle'],
  'black string': ['meche', 'ficelle', 'cordon'], // the brick's fuse
  'blast of air': ['air', 'souffle', 'poumons'],
  blessings: ['benedictions'],
  'blue book': ['livre bleu', 'livre'],
  'blue crystal sphere': ['sphere bleue', 'boule bleue', 'sphere'],
  'blue label': ['etiquette bleue', 'etiquette'],
  box: ['coffre fort', 'coffre'], // the Bank of Zork safe
  'braided wire': ['corde', 'cable', 'fil tresse'],
  brick: ['brique'],
  bridge: ['pont'],
  'broken balloon': ['ballon creve', 'ballon casse', 'ballon'],
  'broken brass lantern': ['lampe cassee', 'lanterne cassee'],
  'cake frosted with blue letters': ['gateau bleu', 'gateau'],
  'cake frosted with green letters': ['gateau vert', 'gateau'],
  'cake frosted with orange letters': ['gateau orange', 'gateau'],
  'cake frosted with red letters': ['gateau rouge', 'gateau'],
  card: ['carte', 'fiche'],
  chasm: ['gouffre', 'abime', 'ravin'],
  'china teapot': ['theiere'],
  'clear crystal sphere': ['sphere transparente', 'boule de cristal', 'sphere'],
  'cloth bag': ['sac', 'sac en tissu', 'sac de toile'],
  compass: ['boussole', 'compas'],
  'crypt door': ['porte de la crypte', 'porte'],
  'dead sea serpent': ['serpent mort', 'serpent'],
  'debris from an explosion': ['debris', 'decombres'],
  degree: ['diplome'],
  // 'cle' is deliberately ambiguous (the FR cle-class trap): both keys.
  'delicate gold key': ['cle', 'cle en or', 'cle doree'],
  demon: ['demon'],
  'diamond shaped window': [
    'fenetre en losange',
    'fenetre brillante',
    'fenetre',
  ],
  'diamond stand': ['socle de diamant', 'socle'],
  'door made of oak': ['porte en chene', 'porte de chene', 'porte'],
  'door partly covered in cobwebs': ['porte aux toiles d araignee', 'porte'],
  'east wall': ['mur est', 'mur'],
  'elvish sword': ['epee', 'epee elfique'],
  'enormous menhir': ['menhir', 'pierre levee'],
  'fancy violin': ['violon'],
  'flathead stamp': ['timbre'],
  footpad: ['bandit', 'voleur', 'malandrin'],
  'frobozz magic grue repellent': ['repulsif', 'repulsif a grue'],
  'gaudy crown': ['couronne'],
  gazebo: ['kiosque', 'gloriette', 'pavillon'],
  'gigantic dog collar': ['collier', 'collier de chien'],
  glacier: ['glacier'],
  'gnome of zurich': ['gnome', 'gnome de zurich'],
  'golden dragon statuette': [
    'statuette',
    'dragon dore',
    'statuette de dragon',
  ],
  'green book': ['livre vert', 'livre'],
  'green piece of paper': ['instructions', 'papier vert', 'papier'],
  ground: ['sol', 'terre'],
  'group of wooden posts': ['poteaux', 'piquets'],
  hedge: ['haie', 'haies'],
  hole: ['fente', 'trou'], // vocab emit is 'slot' (the bank machine slot)
  hook: ['crochet'],
  'huge dead dragon': ['dragon mort', 'dragon'],
  'huge red dragon': ['dragon', 'dragon rouge'],
  keyhole: ['serrure', 'trou de serrure', 'trou de la serrure'],
  lamp: ['lampe', 'lanterne'],
  'large oblong table': ['grande table', 'table'],
  'large stone cube': ['chambre forte', 'cube', 'cube de pierre'], // the vault
  leak: ['fuite'],
  'letter opener': ['coupe papier', 'ouvre lettre'],
  lizard: ['lezard', 'gardien'], // the nasty door keeper
  'lurking grue': ['grue'], // untranslatable proper noun — kept as-is by policy
  'mangled cage': ['cage tordue', 'cage'],
  'marble crypt': ['crypte', 'tombeau'],
  matchbook: ['allumettes', 'pochette d allumettes'],
  'metal lid': ['couvercle'],
  mosses: ['mousse', 'mousses'],
  'narrow crack': ['fissure', 'fente'],
  newspaper: ['journal'],
  'nicked swords': ['epees', 'epees ebrechees'],
  'north wall': ['mur nord', 'mur'],
  'package of candy': ['bonbons', 'friandises', 'paquet de bonbons'],
  'pair of hands': ['mains', 'main'],
  passage: ['sentier', 'chemin', 'piste'], // the forest trail (cf. 'tunnel')
  'pearl necklace': ['collier', 'collier de perles'],
  pentagram: ['pentagramme', 'pentacle'],
  'perfect rose': ['rose', 'rose parfaite'],
  'place mat': ['napperon'],
  'pool of tears': ['mare', 'larmes', 'mare de larmes'],
  'portrait of j. pierpont flathead': ['portrait', 'tableau'],
  'priceless zorkmid': ['piece d or', 'piece', 'zorkmid'], // the gold coin
  'purple book': ['livre violet', 'livre'],
  'quantity of salty water': ['eau salee', 'eau'],
  'quantity of water': ['eau'],
  receptacle: ['recipient', 'receptacle'], // the balloon's fire box
  'red crystal sphere': ['sphere rouge', 'boule rouge', 'sphere'],
  ribbon: ['ruban'],
  robot: ['robot'],
  roses: ['rosier', 'roses'],
  'rotten wooden chest': ['coffre pourri', 'malle', 'coffre'],
  'round button': ['bouton rond', 'bouton'],
  ruby: ['rubis'],
  'ruby stand': ['socle de rubis', 'socle'],
  'rusty iron key': ['cle', 'cle rouillee', 'cle en fer'],
  'safety deposit box': ['coffre de depot', 'coffre bancaire', 'coffre'],
  sailor: ['marin', 'matelot'],
  'sapphire stand': ['socle de saphir', 'socle'],
  'secret door': ['porte secrete', 'porte'],
  'set of poled heads': ['tetes', 'tetes empalees'],
  'set of used wands': ['baguettes', 'baguettes usees'],
  'shimmering curtain of light': ['rideau', 'rideau de lumiere'],
  'small bottles': ['bouteilles', 'petites bouteilles', 'flacons'],
  'smashed trophy cabinet': ['vitrine cassee', 'vitrine brisee', 'vitrine'],
  'solid steel cage': ['cage', 'cage en acier'],
  'south wall': ['mur sud', 'mur'],
  sphere: ['sphere', 'boule'],
  'square button': ['bouton carre', 'bouton'],
  'stack of zorkmid bills': ['billets', 'liasse', 'argent'],
  stairs: ['escalier', 'escaliers', 'marches'],
  'steel box': ['boite en acier', 'boite cabossee', 'boite'],
  'stone door': ['porte de pierre', 'porte en pierre', 'porte'],
  'stoppered glass flask filled with liquid': ['flacon', 'fiole'],
  stream: ['ruisseau'],
  table: ['table'], // the dusty wooden table
  'three-headed dog': ['cerbere', 'chien', 'chien a trois tetes'],
  'triangular button': ['bouton triangulaire', 'bouton'],
  tunnel: ['tunnel', 'passage', 'galerie'], // the dark smoky passage
  unicorn: ['licorne'],
  'volcano gnome': ['gnome du volcan', 'gnome'],
  // NOT 'mur grave': FR 'grave' false-friends EN 'grave' (the marble crypt
  // synonym) — that would hijack a cross-canonical word, so reworded.
  'wall with etchings': ['gravures', 'mur aux gravures'],
  'warning label': ['etiquette', 'avertissement'],
  water: ['eau'],
  well: ['puits'],
  'west wall': ['mur ouest', 'mur'],
  'white book': ['livre blanc', 'livre'],
  wish: ['voeu', 'souhait'],
  'wizard of frobozz': ['magicien', 'sorcier'],
  "wizard's magic wand": ['baguette', 'baguette magique'],
  "wizard's trophy cabinet": ['vitrine', 'vitrine a trophees', 'armoire'],
  "wizard's workbench": ['etabli'],
  'wooden bucket': ['seau'],
  'wooden club': ['massue', 'gourdin'],
  zorkmid: ['zorkmid'], // untranslatable currency proper noun
}
