// src/llm/lexicon/walkthrough-commands.ts
// Curated winning-command lists for the walkthrough-reachability gate
// (walkthrough-coverage.test.ts). The gate's premise: every verb and object a
// player MUST type to COMPLETE the game has to be reachable in every input
// language — anything off the winning path needs no coverage argument.
//
// Zork I is parsed live from docs/walkthrough-zork-i.txt (clean ">command"
// lines), so it isn't duplicated here. Zork II and III walkthroughs are prose
// with commands embedded in quotes / CAPS, NOT machine-parseable, so their
// required commands are transcribed by hand from:
//   docs/walkthrough-zork-ii.txt  (Infocom "complete solution")
//   docs/walkthrough-zork-iii.txt (Darrell Wong, GameFAQs, 2001)
// Pure movement (compass + up/down/in/out) is omitted — directions.ts owns it
// and directions.test.ts already gates every listed language. Each entry is a
// full command so the gate can extract both the verb (head) and the objects.

/** Zork II — The Wizard of Frobozz. Required commands, movement elided. */
export const ZORK2_COMMANDS: readonly string[] = [
  'take all',
  'light lamp',
  'enter gazebo',
  'take teapot',
  'exit',
  'fill teapot',
  'say a well', // riddle-room answer
  'take pearls',
  'get into bucket',
  'pour water',
  'get out',
  'take red cake',
  'take blue cake',
  'take green cake',
  'eat green cake',
  'throw red cake into pool',
  'take candy',
  'eat blue cake',
  'tell robot go east',
  'tell robot push triangle',
  'tell robot go south',
  'take sphere',
  'tell robot lift cage',
  'drop teapot',
  'open box',
  'take violin',
  'drop all but lamp and sword',
  'take mat and opener',
  'take brick',
  'put mat under door',
  'open lid',
  'put opener in hole',
  'take mat',
  'take key',
  'take opener',
  'unlock door with key',
  'open door',
  'take newspaper and matches',
  'take string',
  'attack dragon',
  'take ruby',
  'get into basket',
  'open receptacle',
  'put paper in receptacle',
  'light match',
  'light paper with match',
  'wait',
  'tie wire to hook',
  'take coin',
  'open purple book',
  'take stamp',
  'untie wire',
  'put string on brick',
  'put brick in hole',
  'light string with match',
  'take crown',
  'close receptacle',
  'take chest',
  'kiss princess',
  'open chest',
  'again',
  'take dragon',
  'drop chest and rose',
  'take club',
  'feed lizard candy',
  'unlock door with gold key',
  'take portrait',
  'enter light',
  'enter south wall',
  'take bills',
  'kill',
  'take lamp',
  'throw club at glass',
  'take white sphere',
  'put white sphere on diamond stand',
  'put red sphere on ruby stand',
  'put blue sphere on sapphire stand',
  'take black sphere',
  'put sphere in circle',
  'give all but lamp to demon',
  'tell demon give me wand',
  'take wand',
  'point wand at menhir',
  'say float',
  'take collar',
  'put collar on dog',
  'turn off lamp',
  'open secret door',
]

/** Zork III — The Dungeon Master. Required commands, movement elided. */
export const ZORK3_COMMANDS: readonly string[] = [
  'get lantern',
  'turn on lantern',
  'enter lake',
  'get torch',
  'wait',
  'touch table',
  'get can',
  'open cover',
  'get key',
  'spray grue repellent on self',
  'attack figure with sword',
  'get hood',
  'get cloak',
  'get bread',
  'tie chest to rope',
  'grab rope',
  'say hello sailor',
  'get vial',
  'push gold machine south',
  'open stone door',
  'push machine east',
  'turn dial to 776',
  'enter machine',
  'push button',
  'get ring',
  'open door',
  'open wooden door',
  'put ring under seat',
  'enter gold machine',
  'get out',
  'look under seat',
  'get all',
  'push south wall',
  'get book',
  'wake man',
  'give bread',
  'put sword in beam',
  'raise short pole',
  'push white panel',
  'push pine panel',
  'open vial',
  'drink liquid',
  'knock on door',
  'turn dial to 4',
  'unlock bronze door with key',
  'open bronze door',
]
